experiment_name: lacuna_moe_synthetic_training
output_dir: /mnt/artifacts/project_lacuna/models/checkpoints
num_train_epochs: 10
per_device_train_batch_size: 16
per_device_eval_batch_size: 32
learning_rate: 2.0e-05
warmup_steps: 1000
weight_decay: 0.01
evaluation_strategy: steps
eval_steps: 500
save_steps: 1000
logging_steps: 100
fp16: true
gradient_checkpointing: true
dataloader_num_workers: 4
